name: ClientPortal
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-scan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0

      - name: build Docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          push: false
          tags: client-portal-build-scan:${{ github.sha }}
          load: true
    
      - name: run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'client-portal-build-scan:${{ github.sha }}'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'
          format: 'table'

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0

      - name: build Docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          push: false
          tags: client-portal-tests:${{ github.sha }}
          load: true
# 
#       - name: run tests
#         run: |
#           docker run --rm client-portal-tests:${{ github.sha }} pytest /app/ClientPortal/tests/just-a-test.py

