name: ClientPortal
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  client-portal:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.2
        
      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v4.0.0

      - name: build Docker image
        uses: docker/build-push-action@v7.0.0
        with:
          context: .
          push: false
          tags: client-portal:${{ github.sha }}
          load: true
    
      - name: run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'client-portal:${{ github.sha }}'
          exit-code: '0'
          severity: 'CRITICAL,HIGH,MEDIUM'
          format: 'table'
                
